version: '3.8'

services:
  nginx:
    image: nginx:latest
      # openresty/openresty:alpine
      # nginx:latest
    restart: always

    container_name: nginxnode2
    # ports:
    #   - "127.0.0.1:8888:80"

    volumes:

      - ./conf/oauth2.conf:/etc/nginx/conf.d/default.conf
      - ./cors.conf:/etc/nginx/cors.conf
      - ./nginx.conf:/etc/nginx/nginx.conf

      - /var/www/build:/var/www
      - ./logs:/var/log/nginx

    network_mode: host
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.9.0
    container_name: oauth2-proxy
    restart: always
    network_mode: host
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_LOGGING_LEVEL=debug
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://127.0.0.1:8080/realms/master
      - OAUTH2_PROXY_CLIENT_ID=myclent
      #oauth2-proxy
      - OAUTH2_PROXY_CLIENT_SECRET=9nv7PUBNyr3TB9FpwjO1gPbM2rDA0ELF # Замените на секрет из Keycloak
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:8888/oauth2/callback
      - OAUTH2_PROXY_COOKIE_SECRET=b71b15852a8ccc6304874697ab70d276 # Сгенерируйте: openssl rand -base64 32
      - OAUTH2_PROXY_COOKIE_NAME=_oauth2_proxy
      - OAUTH2_PROXY_UPSTREAMS=http://127.0.0.1:8082
      - OAUTH2_PROXY_HTTP_ADDRESS=127.0.0.1:4180  # 0.0.0.0 для доступа снаружи
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_CORS_ALLOWED_ORIGINS=http://localhost:3000
      - OAUTH2_PROXY_CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,PATCH,OPTIONS
      - OAUTH2_PROXY_CORS_ALLOWED_HEADERS=Authorization,Content-Type,X-Requested-With
      - OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY=true # Для тестов, отключите в продакшене
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_OIDC_GROUPS_CLAIM=groups
      - OAUTH2_PROXY_ALLOWED_GROUPS=superadmin # Ограничиваем доступ только для групп, например, admin
      - OAUTH2_PROXY_EMAIL_DOMAINS=* # Разрешаем все email-адреса
