version: "3"
services:

  # nifi:
  #   hostname: nifi.geekslore.ru
  #   image: apache/nifi:latest
  #   ports:
      # - "0.0.0.0:8443:8443" # Unsecured HTTP Web Port
  #     - "0.0.0.0:8080:8080"
  #   volumes:
  #     - /opt/nifi/drivers:/opt/nifi/drivers

   zookeeper:
        hostname: myzookeeper
        container_name: zookeeper_container_persistent
        image: 'bitnami/zookeeper:3.7.0'  # latest image as of 2021-11-09.
        restart: on-failure
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - my_persistent_network
# version control for nifi flows
    registry:

        hostname: myregistry
        container_name: registry
        image: 'apache/nifi-registry:1.15.0'  # latest image as of 2021-11-09.
        restart: on-failure
        ports:
            - "18080:18080"
        environment:
            - LOG_LEVEL=INFO
            - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/nifi-registry-current/database
            - NIFI_REGISTRY_FLOW_PROVIDER=file
            - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
        volumes:
            - /opt/nifi_registry/database:/opt/nifi-registry/nifi-registry-current/database
            - /opt/nifi_registry/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
        # networks:
        #     - my_persistent_network
# data extraction, transformation and load service
  nifi:
        hostname: nifi.geekslore.ru
        #hostname: mynifi
        #container_name: nifi_container_persistent
        image: 'apache/nifi:latest'  # latest image as of 2021-11-09.
        restart: on-failure
        ports:
          - "0.0.0.0:8443:8443" # Unsec
            # - '8091:8080'
        environment:
            # - NIFI_WEB_HTTP_PORT=8080
            - NIFI_CLUSTER_IS_NODE=true
            - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
            - NIFI_ZK_CONNECT_STRING=myzookeeper:2181
            - NIFI_ELECTION_MAX_WAIT=30 sec
            - NIFI_SENSITIVE_PROPS_KEY='12345678901234567890A'
        healthcheck:
            test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:8091/nifi/}"
            interval: "60s"
            timeout: "3s"
            start_period: "5s"
            retries: 5
        volumes:
            - /opt/nifi/database_repository:/opt/nifi/nifi-current/database_repository
            - /opt/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
            - /opt/nifi/content_repository:/opt/nifi/nifi-current/content_repository
            - /opt/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
            - /opt/nifi/state:/opt/nifi/nifi-current/state
            - /opt/nifi/logs:/opt/nifi/nifi-current/logs
            # uncomment the next line after copying the /conf directory from the container to your local directory to persist NiFi flows
            #- ./nifi/conf:/opt/nifi/nifi-current/conf
        # networks:
        #     - my_persistent_network


  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
      #  nexus.bia-tech.ru/mssql/server:2022-latest

    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Passw0rd'

      MSSQL_DATA_DIR: /var/opt/mssql/dat
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - /var/data/mssql:/var/opt/mssql/data
      - /var/data/mssql-log:/var/opt/mssql/log
      - /var/data/mssql-secrets:/var/opt/mssql/secrets
#jdbc:sqlserver://;servername=mssql-db;port=1433;database=mydb;authentication=NotSpecified;
#encrypt=true;
#integratedSecurity=true;

#      /opt/mssql-tools18/bin/sqlcmd -S 127.0.0.1 -U SA -P 'Passw0rd' -C
#/opt/nifi/nifi-current$ ./nifi.sh set-single-user-credentials admin Exb021205Nifi!
#    network_mode: "host"
#    environment:
#       NIFI_WEB_HTTP_HOST: "http://185.146.157.69"
#       NIFI_WEB_HTTPS_HOST: "https://185.146.157.69"
#       NIFI_WEB_HTTP_PORT: 8080
#       NIFI_WEB_HTTPS_PORT: 8443
 #     - NIFI_CLUSTER_IS_NODE=true
 #     - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
 #     - NIFI_ZK_CONNECT_STRING=zookeeper:2181
 #     - NIFI_ELECTION_MAX_WAIT=1 min
