version: "3"
services:
#  zookeeper:
#    hostname: zookeeper
#    container_name: zookeeper
#    image: 'bitnami/zookeeper:latest'
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
  nifi:
    hostname: nifi.geekslore.ru
    image: apache/nifi:latest
    ports:
      - "0.0.0.0:8443:8443" # Unsecured HTTP Web Port
      - "0.0.0.0:8080:8080"

  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
      #  nexus.bia-tech.ru/mssql/server:2022-latest
    volumes:
      - /opt/nifi/drivers:/opt/nifi/drivers
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Passw0rd'

      MSSQL_DATA_DIR: /var/opt/mssql/dat
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - /var/data/mssql:/var/opt/mssql/data
      - /var/data/mssql-log:/var/opt/mssql/log
      - /var/data/mssql-secrets:/var/opt/mssql/secrets
#jdbc:sqlserver://;servername=mssql-db;port=1433;database=mydb;authentication=NotSpecified;
#encrypt=true;
#integratedSecurity=true;

#      /opt/mssql-tools18/bin/sqlcmd -S 127.0.0.1 -U SA -P 'Passw0rd' -C
#/opt/nifi/nifi-current$ ./nifi.sh set-single-user-credentials admin Exb021205Nifi!
#    network_mode: "host"
#    environment:
#       NIFI_WEB_HTTP_HOST: "http://185.146.157.69"
#       NIFI_WEB_HTTPS_HOST: "https://185.146.157.69"
#       NIFI_WEB_HTTP_PORT: 8080
#       NIFI_WEB_HTTPS_PORT: 8443
 #     - NIFI_CLUSTER_IS_NODE=true
 #     - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
 #     - NIFI_ZK_CONNECT_STRING=zookeeper:2181
 #     - NIFI_ELECTION_MAX_WAIT=1 min
