concurrent = 4
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-runner"
  url = "http://gitlab/"
  token = ""
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "ubuntu:22.04"
    privileged = true
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]

    #gitlab-runner register  --url http://mds-gitlab.npobaum.ru  --token glrt-qSra9SqmSZYt7ADkkXkR
