version: '3'

services:
  kafka:
      restart: unless-stopped
      image: bitnami/kafka:3.5.1
      hostname: kafka-1
      container_name: kafka1
      # ports:
      #   - "39092:39092"
      environment:
        - KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
        - KAFKA_CFG_NODE_ID=1
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
        - KAFKA_CFG_LISTENERS=SASL_SSL://:19092,EXTERNAL://:39092,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,EXTERNAL:SASL_SSL
        - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:19092,EXTERNAL://:39092
        - KAFKA_CLIENT_USERS=admin
        - KAFKA_CLIENT_PASSWORDS=admin
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
        - KAFKA_CONTROLLER_USER=controller_user
        - KAFKA_CONTROLLER_PASSWORD=controller_password
        - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_SSL
        - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
        - KAFKA_INTER_BROKER_USER=controller_user
        - KAFKA_INTER_BROKER_PASSWORD=controller_password
        - KAFKA_CERTIFICATE_PASSWORD=12345678
        - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
        - KAFKA_TLS_TYPE=JKS
        - KAFKA_HEAP_OPTS=-Xmx8G -Xms8G
        - KAFKA_JVM_PERFORMANCE_OPTS=-XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80
        - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=u-p-bi-kafka-1.srv.bia-tech.ru -Dcom.sun.management.jmxremote.rmi.port=9997
        - JMX_PORT=9997


      volumes:
        - '/opt/data/kafka:/bitnami/kafka'
        - '/opt/certs/kafka.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
        - '/opt/certs/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
      user: "0"
  kafka2:
      restart: unless-stopped
      image: bitnami/kafka:3.5.1
      hostname: kafka-2
      container_name: kafka2
      # ports:
      #   - "39092:39092"
      environment:
        - KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
        - KAFKA_CFG_NODE_ID=2
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
        - KAFKA_CFG_LISTENERS=SASL_SSL://:19092,EXTERNAL://:39092,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,EXTERNAL:SASL_SSL
        - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:19092,EXTERNAL://:39092
        - KAFKA_CLIENT_USERS=admin
        - KAFKA_CLIENT_PASSWORDS=admin
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
        - KAFKA_CONTROLLER_USER=controller_user
        - KAFKA_CONTROLLER_PASSWORD=controller_password
        - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_SSL
        - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
        - KAFKA_INTER_BROKER_USER=controller_user
        - KAFKA_INTER_BROKER_PASSWORD=controller_password
        - KAFKA_CERTIFICATE_PASSWORD=12345678
        - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
        - KAFKA_TLS_TYPE=JKS
        - KAFKA_HEAP_OPTS=-Xmx8G -Xms8G
        - KAFKA_JVM_PERFORMANCE_OPTS=-XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80
        - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=u-p-bi-kafka-1.srv.bia-tech.ru -Dcom.sun.management.jmxremote.rmi.port=9997
        - JMX_PORT=9997


      volumes:
        - '/opt/data/kafka2:/bitnami/kafka'
        - '/opt/certs/kafka.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
        - '/opt/certs/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
      user: "0"
  kafka3:
      restart: unless-stopped
      image: bitnami/kafka:3.5.1
      hostname: kafka-3
      container_name: kafka3
      # ports:
      #   - "39092:39092"
      environment:
        - KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
        - KAFKA_CFG_NODE_ID=3
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
        - KAFKA_CFG_LISTENERS=SASL_SSL://:19092,EXTERNAL://:39092,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,EXTERNAL:SASL_SSL
        - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:19092,EXTERNAL://:39092
        - KAFKA_CLIENT_USERS=admin
        - KAFKA_CLIENT_PASSWORDS=admin
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
        - KAFKA_CONTROLLER_USER=controller_user
        - KAFKA_CONTROLLER_PASSWORD=controller_password
        - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_SSL
        - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
        - KAFKA_INTER_BROKER_USER=controller_user
        - KAFKA_INTER_BROKER_PASSWORD=controller_password
        - KAFKA_CERTIFICATE_PASSWORD=12345678
        - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
        - KAFKA_TLS_TYPE=JKS
        - KAFKA_HEAP_OPTS=-Xmx8G -Xms8G
        - KAFKA_JVM_PERFORMANCE_OPTS=-XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80
        - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=u-p-bi-kafka-1.srv.bia-tech.ru -Dcom.sun.management.jmxremote.rmi.port=9997
        - JMX_PORT=9997


      volumes:
        - '/opt/data/kafka3:/bitnami/kafka'
        - '/opt/certs/kafka.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
        - '/opt/certs/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
      user: "0"
      # network_mode: "host"

  # schema-registry:
  #     image: confluentinc/cp-schema-registry:7.2.5
  #     #hostname: schema-registry
  #       #ports:
  #       #- "8081:8081"
  #     environment:
  #       - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=u-p-bi-kafka-1.srv.bia-tech.ru:19092,u-p-bi-kafka-2.srv.bia-tech.ru:19092,u-p-bi-kafka-3.srv.bia-tech.ru:19092
  #       - SCHEMA_REGISTRY_HOST_NAME=kafka-1
  #       - SCHEMA_REGISTRY_LISTENERS=https://0.0.0.0:8081
  #       - SCHEMA_REGISTRY_DEBUG=true
  #       - SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION=/etc/schema-registry/certs/kafka.keystore.jks
  #       - SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD=12345678
  #       - SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION=/etc/schema-registry/certs/kafka.truststore.jks
  #       - SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD=12345678
  #       - SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD=12345678
  #       # - SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: |
  #       #         org.apache.kafka.common.security.plain.PlainLoginModule required \
  #       #         username="admin" \
  #       #         password="admin";
  #       - SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";
  #       - SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM=PLAIN
  #       - SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=SASL_SSL
  #       - SCHEMA_REGISTRY_KAFKASTORE_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
  #       - SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION=/etc/schema-registry/certs/schema-registry.server.truststore.jks
  #       - SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD=changeit
  #       - SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION=/etc/schema-registry/certs/schema-registry.server.keystore.jks
  #       - SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD=changeit
  #       - SCHEMA_REGISTRY_SSL_KEY_PASSWORD=changeit
  #       - SCHEMA_REGISTRY_SSL_CLIENT_AUTHENTICATION=NONE
  #       - SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL=https
  #       - SCHEMA_REGISTRY_KAFKASTORE_TOPIC=_schemas
  #
  #     volumes:
  #       - '/var/lib/schema-registry:/etc/schema-registry'
  #       - './certs/schema-registry.server.keystore.jks:/etc/schema-registry/certs/schema-registry.server.keystore.jks:ro'
  #       - './certs/schema-registry.server.truststore.jks:/etc/schema-registry/certs/schema-registry.server.truststore.jks:ro'
  #       - './certs:/etc/schema-registry/certs:ro'
  #
  #     user: "0"
  #     network_mode: "host"
