version: "3.9"
services:

  nginx:
    image: nginx
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80


  exporter:
    hostname:  exporter
    image: nginx/nginx-prometheus-exporter
    environment:
      # ZOOKEEPER_CLIENT_PORT: 22181
      # ZOOKEEPER_SASL_ENABLED: "false"
      # ZOOKEEPER_TICK_TIME: 2000
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - 9113:9113
    # volumes:
    #   - /data/kafka/files/:/opt/files
    #   - /data/zookeeper/data:/var/lib/zookeeper/data

#
