version: "3.9"
services:

  mirror:
    build: ./
    # container_name: kafka-ui
    ports:
     - 8181:80
    restart: always
    volumes:
      - ./baseos:/mirror/baseos
      - ./appstream:/mirror/appstream
