version: "3.9"
services:
  proxy:
    image: ubuntu/squid:5.2-22.04_beta

      #datadog/squid
    ports:
     - 192.168.0.3:3128:3128
    volumes:
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./cache:/var/spool/squid
      # - ./logs:/var/log/squid

#   mirror:
#     build: ./
#     # container_name: kafka-ui
#     ports:
#      - 8181:80
#     restart: always
#     volumes:
#       - mirror:/mirror
# volumes:
#   mirror:
