# Generated by Django 5.0.6 on 2024-05-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etl_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Etl_load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parquete_file', models.CharField(max_length=200)),
                ('min_id', models.IntegerField()),
                ('max_id', models.IntegerField()),
                ('table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.etl_table')),
            ],
        ),
    ]
