version: '3.7'
services:


  minio:
    image:  bitnami/minio:latest
    network_mode: "host"
    environment:
      - MINIO_DATA_DIR=/data
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123

    volumes:
      - /data:/data
