version: "3.9"
services:
### Kafka Exporter #########################################
  kafka-exporter:
    container_name: kafka-exporter
    image: danielqsj/kafka-exporter
    restart: unless-stopped
    depends_on:
      - kafka

    #command: ["--kafka.server=mq:9092"]
    command: ["--kafka.server=10.182.19.20:29092",  "--sasl.enabled", "--sasl.username=admin", "--sasl.password=admin-secret", "--sasl.mechanism=plain"]

#sasl.enabled	false	Connect using SASL/PLAIN
#sasl.handshake	true	Only set this to false if using a non-Kafka SASL proxy
#sasl.username		SASL user name
#sasl.password		SASL user password
#sasl.mechanism		SASL mechanism can be plain, scram-sha512, scram-sha256
    ports:
      - "9308:9308"
#    networks:
#     - services
    #mem_limit: 128m
    #mem_reservation: 64m
    logging:
        driver: "json-file"
        options:
          max-size: "5m"
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      #- KAFKA_CLUSTERS_0_NAME=local
      #- KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=10.182.19.20:29092
      #- KAFKA_CLUSTERS_0_ZOOKEEPER=10.182.19.20:22181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 10.182.19.20:29092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
      DYNAMIC_CONFIG_ENABLED: "true" # not necessary for sasl auth, added for tests


  zookeeper:
    hostname:  zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_SASL_ENABLED: "false"
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - 22181:22181
    volumes:
      - /data/kafka/files/:/opt/files
      - /data/zookeeper/data:/var/lib/zookeeper/data

#10.182.19.20
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
#      - 9141:9141
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 10.182.19.20:22181
      ZOOKEEPER_SASL_ENABLED: "false"
      #KAFKA_OPTS: "-javaagent:/opt/jmx/jmx_prometheus_javaagent-0.12.0.jar=9141:/opt/jmx/kafka-2_0_0.yml"
      #ADD SASL
      #KAFKA_SASL_ENABLED_MECHANISMS: "SCRAM-SHA-256,SCRAM-SHA-512"
      KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:29092
      #,BROKER://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://10.182.19.20:29092
      #,BROKER://kafka:9092
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN

      ##KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      ##KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      #KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      #KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      #KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      #KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
# for older kafka versions use this instead
      #KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_SUPER_USERS: "User:admin"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/files/jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      #KAFKA_INTER_BROKER_LISTENER_NAME: BROKER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      #- ./files:/opt/jmx
      - /data/kafka/files/:/opt/files
      - /data/kafka/data:/var/lib/kafka/data
#jmx_prometheus_javaagent-0.12.0.jar
#kafka-2_0_0.yml
