version: '3.8'

services:
  nginx:
    image: openresty/openresty:alpine
      # nginx:latest
    restart: always

    container_name: nginxnode
    # ports:
      - "80:80"
    environment:
     - client_auth_basic=bXljbGllbnQ6djdQVUJOeXIzVEI5RnB3ak8xZ1BiTTJyREEwRUxG
     - KEYCLOAK_URL="http://keycloak:8080"
     - KEYCLOAK_REALM=master
     - KEYCLOAK_CLIENT_ID=myclient
     - KEYCLOAK_CLIENT_SECRET=bXljbGllbnQ6djdQVUJOeXIzVEI5RnB3ak8xZ1BiTTJyREEwRUxG
     - BACKEND_SERVICE="http://127.0.01:8080"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./cors.conf:/etc/nginx/cors.conf
      - ./pre.conf:/etc/nginx/pre.conf
      - ./api_security.conf:/etc/nginx/api_security.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/var/www
      - ./logs:/var/log/nginx
    # depends_on:
    #   - keycloak-node1
    #   - keycloak-node2
    # network_mode: host
  back:

    build:
      context: back
      dockerfile: .

    container_name: back
    hostname: back
    restart: always
    # network_mode: host
    user: nobody:nogroup
    environment:
      - PORT=8082

  openldap:
    image: bitnami/openldap:2.5.16
    user: root
    container_name: openldap
    # network_mode: host
    restart: always
    environment:

      - BITNAMI_DEBUG=true
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword  # Только этот пароль!

    ports:
      - "389:1389"
      - "636:1636"
    volumes:
      # - openldap_data:/bitnami/openldap
      - ./ldap:/bitnami/openldap

  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    environment:
      - POSTGRESQL_DATABASE=keycloak
      - POSTGRESQL_USERNAME=keycloak_user
      - POSTGRESQL_PASSWORD=keycloak_password
    volumes:
      # - postgresql_data:/bitnami/postgresql
      - /opt/pgdata:/bitnami/postgresql
    # network_mode: host
    restart: always

  keycloak-node1:
    image: bitnami/keycloak:latest
    hostname: keycloak
    container_name: keycloak-node1
    environment:
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KEYCLOAK_DATABASE_HOST=keycloak
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak_user
      - KEYCLOAK_DATABASE_PASSWORD=keycloak_password
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminpassword
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_HTTPS_PORT=8443
      - KEYCLOAK_PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_CACHE=ispn
    #   - JGROUPS_DISCOVERY_PROTOCOL=TCP
    #   - JGROUPS_DISCOVERY_PROPERTIES=initial_hosts=keycloak[7600],keycloak2[7600],keycloak3[7600]
    # # ports:
    #   - "8081:8080"
    depends_on:
      - postgresql
    # network_mode: host
    restart: always
