TOKEN="eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2Mjg4MDBlZi0wYmQ3LTQyODctYTg5OC0zOTI5NTU3MjYwMzEifQ.eyJleHAiOjE3NDczMDk1NTksImlhdCI6MTc0NzMwNzc1OSwianRpIjoiNjYyMDFkNjYtZmE4My00MjRiLThlMzktOTYwMWQ2NDc4YTc3IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdC9yZWFsbXMvbWFzdGVyIiwic3ViIjoiMjdjN2NhOTEtYTYwMi00N2MwLTlhOGUtNDlhMmNjMzE1MzExIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6Im15Y2xpZW50Iiwic2lkIjoiN2QwNzUyNGEtNDBmMC00YmJiLTgzYjEtNzFmY2MzMWYyZDI2Iiwic2NvcGUiOiJ3ZWItb3JpZ2lucyBlbWFpbCBwcm9maWxlIGFjciBiYXNpYyByb2xlcyJ9.gK09zE2D5itVa7vdUkolH5tdbebTJANXtkNWOSBsuGm1Ptde3l5cO_GT9gLlHNqkFoh74L85zPA_T6BbmmCi6w"
SECRET="rNEoR0SaH6ImZGEwfqEY4zVqocs58gMW"
#curl -v -X POST 'http://localhost/realms/master/protocol/openid-connect/token' \
#  -d "grant_type=refresh_token&client_id=myclient&client_secret=$SECRET&refresh_token=$TOKEN"

curl -v -X POST "http://172.16.1.153/api/realms/master/protocol/openid-connect/token" \
 -d "grant_type=refresh_token&client_id=myclient&client_secret=$SECRET&refresh_token=$TOKEN"
