# version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA="/var/lib/postgresql/data/pgdata"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

    volumes:
      # - ../2. Init Database:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
      - /tmp:/tmp
    ports:
      - "5432:5432"
