services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER:  airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      PGDATA: "/var/lib/postgresql/data/pgdata"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

    volumes:
      # - ../2. Init Database:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
      - /tmp:/tmp
      - ./sql:/opt/sql
    ports:
      - "5432:5432"
volumes:
  pgdata:
